session_name: workspace-saas-prod
start_directory: ..

windows:
  - window_name: stack
    panes:
      - docker compose --env-file .env -f docker-compose.yml up --build

  - window_name: backend
    layout: even-vertical
    panes:
      - shell_command:
          - sleep 5
          - docker compose --env-file .env -f docker-compose.yml logs -f backend
      - shell_command:
          - sleep 8
          - docker compose exec backend sh

  - window_name: frontend
    layout: even-vertical
    panes:
      - shell_command:
          - sleep 5
          - docker compose --env-file .env -f docker-compose.yml logs -f frontend
      - shell_command:
          - sleep 8
          - docker compose exec frontend sh

  - window_name: db
    layout: even-vertical
    panes:
      - shell_command:
          - sleep 5
          - docker compose --env-file .env -f docker-compose.yml logs -f db
      - shell_command:
          - sleep 8
          - docker compose exec db sh
